export enum BankPosition {
    TELLER = "TELLER",
    SHIFT_SUPERVISOR = "SHIFT_SUPERVISOR",
    ASSISTANT_MANAGER = "ASSISTANT_MANAGER",
    HUMAN_RESOURCE = "HUMAN_RESOURCE",
    GENERAL_MANAGER = "GENERAL_MANAGER",
    IT_SUPPORT = "IT_SUPPORT",
    CFO ="CFO",
    CTO = "CTO",
    CEO = "CEO"
}